/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerenIndustrialCraiovaRouteImport } from './routes/teren-industrial-craiova'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ParcIndustrialCraiovaRouteImport } from './routes/parc-industrial-craiova'
import { Route as LogisticaCraiovaRouteImport } from './routes/logistica-craiova'
import { Route as HaleDepoziteCraiovaRouteImport } from './routes/hale-depozite-craiova'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as IndexRouteImport } from './routes/index'

const TerenIndustrialCraiovaRoute = TerenIndustrialCraiovaRouteImport.update({
  id: '/teren-industrial-craiova',
  path: '/teren-industrial-craiova',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcIndustrialCraiovaRoute = ParcIndustrialCraiovaRouteImport.update({
  id: '/parc-industrial-craiova',
  path: '/parc-industrial-craiova',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticaCraiovaRoute = LogisticaCraiovaRouteImport.update({
  id: '/logistica-craiova',
  path: '/logistica-craiova',
  getParentRoute: () => rootRouteImport,
} as any)
const HaleDepoziteCraiovaRoute = HaleDepoziteCraiovaRouteImport.update({
  id: '/hale-depozite-craiova',
  path: '/hale-depozite-craiova',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/hale-depozite-craiova': typeof HaleDepoziteCraiovaRoute
  '/logistica-craiova': typeof LogisticaCraiovaRoute
  '/parc-industrial-craiova': typeof ParcIndustrialCraiovaRoute
  '/privacy': typeof PrivacyRoute
  '/teren-industrial-craiova': typeof TerenIndustrialCraiovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/hale-depozite-craiova': typeof HaleDepoziteCraiovaRoute
  '/logistica-craiova': typeof LogisticaCraiovaRoute
  '/parc-industrial-craiova': typeof ParcIndustrialCraiovaRoute
  '/privacy': typeof PrivacyRoute
  '/teren-industrial-craiova': typeof TerenIndustrialCraiovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/hale-depozite-craiova': typeof HaleDepoziteCraiovaRoute
  '/logistica-craiova': typeof LogisticaCraiovaRoute
  '/parc-industrial-craiova': typeof ParcIndustrialCraiovaRoute
  '/privacy': typeof PrivacyRoute
  '/teren-industrial-craiova': typeof TerenIndustrialCraiovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/hale-depozite-craiova'
    | '/logistica-craiova'
    | '/parc-industrial-craiova'
    | '/privacy'
    | '/teren-industrial-craiova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/hale-depozite-craiova'
    | '/logistica-craiova'
    | '/parc-industrial-craiova'
    | '/privacy'
    | '/teren-industrial-craiova'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/hale-depozite-craiova'
    | '/logistica-craiova'
    | '/parc-industrial-craiova'
    | '/privacy'
    | '/teren-industrial-craiova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  HaleDepoziteCraiovaRoute: typeof HaleDepoziteCraiovaRoute
  LogisticaCraiovaRoute: typeof LogisticaCraiovaRoute
  ParcIndustrialCraiovaRoute: typeof ParcIndustrialCraiovaRoute
  PrivacyRoute: typeof PrivacyRoute
  TerenIndustrialCraiovaRoute: typeof TerenIndustrialCraiovaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teren-industrial-craiova': {
      id: '/teren-industrial-craiova'
      path: '/teren-industrial-craiova'
      fullPath: '/teren-industrial-craiova'
      preLoaderRoute: typeof TerenIndustrialCraiovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parc-industrial-craiova': {
      id: '/parc-industrial-craiova'
      path: '/parc-industrial-craiova'
      fullPath: '/parc-industrial-craiova'
      preLoaderRoute: typeof ParcIndustrialCraiovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica-craiova': {
      id: '/logistica-craiova'
      path: '/logistica-craiova'
      fullPath: '/logistica-craiova'
      preLoaderRoute: typeof LogisticaCraiovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hale-depozite-craiova': {
      id: '/hale-depozite-craiova'
      path: '/hale-depozite-craiova'
      fullPath: '/hale-depozite-craiova'
      preLoaderRoute: typeof HaleDepoziteCraiovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  HaleDepoziteCraiovaRoute: HaleDepoziteCraiovaRoute,
  LogisticaCraiovaRoute: LogisticaCraiovaRoute,
  ParcIndustrialCraiovaRoute: ParcIndustrialCraiovaRoute,
  PrivacyRoute: PrivacyRoute,
  TerenIndustrialCraiovaRoute: TerenIndustrialCraiovaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
